services:
  - type: web
    name: gemini-mind-reader-mcp
    env: node
    region: oregon
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    healthCheckPath: /
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: gemini-mind-reader-mcp
          property: port
      - key: HOST
        value: 0.0.0.0
      - key: GEMINI_API_KEY
        value: AIzaSyC0IpjMzBHq999z3Nze1q673UEHCbCJCWg
